Debug overlay
SolastaMods/SolastaModApi pull request #11
Opened 2021-11-09 14:25 UTC by ThyWoof

. adds toggle to enable in game debug menu
. adds toggle to enable debug camera

2021-11-09 23:07 UTC, ChrisPJohn requested changes
Some questions and clean up.

Another thought I had is would either of these make sense in the Community Expansion?

2021-11-09 23:07 UTC, ChrisPJohn commented on SolastaModApi/Viewers/SettingsViewer.cs
> +                ServiceRepository.GetService<IDebugOverlayService>().ToggleActivation();
Should this be set based on the toggle position, rather than just calling toggle? Is there a chance the bool and the overlay state can get out of sync?

2021-11-09 23:07 UTC, ChrisPJohn commented on SolastaModApi/Viewers/SettingsViewer.cs
> +if (service1 == null || service2 == null)
Should this be removed?

2021-11-09 23:07 UTC, ChrisPJohn commented on SolastaModApi/Viewers/SettingsViewer.cs
> +                if (viewService == null || cameraService == null)
Should we only show the toggle if the services are available?

2021-11-10 01:39 UTC, ThyWoof commented
moving this over to CE

2021-11-10 01:39 UTC, closed without merging